# This GitHub build and deploy, runs on master publish.
#  - Installs Dart and flutter.
#  - Shows used dart and flutter version.
#  - Enables flutter web.
#  - Gets package dependencies.
#  - Run dart analyze.
#  - Show outdated packages.
#  - Verify that dart format is used by all committed code, fail if not.
#  - Build default and web example apps for FlexColorPicker.
#    - Flutter clean.
#    - Flutter build web app, in release mode and with CanvasKit renderer.
#    - Deploy to GitHub page
name: Build and Deploy Web ThemeDemo
on:
  push:
    branches: [none]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [none]
    paths-ignore:
      - "**.md"
  release:
    branches: [none]
    types: [published]
    paths-ignore:
      - "**.md"
jobs:
  tests_build:
    name: Analyze, build and deploy ThemeDemo web app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter and Dart SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Show Dart SDK version
        run: dart --version

      - name: Show Flutter SDK version
        run: flutter --version

      - name: Flutter Enable Web
        run: flutter config --enable-web

      - name: Install Flutter package dependencies
        run: flutter pub get

      - name: Analyze Dart source
        run: dart analyze

      - name: Show outdated packges
        run: flutter pub outdated

      - name: Verify that Dart formatting is used, fail if not
        run: dart format --output=none --set-exit-if-changed .

      - name: WEB release build using CanvasKit
        run: flutter build web --web-renderer=canvaskit --base-href "/themedemo/" --release --target=lib/main.dart

      - name: WEB Deploy to GitHub Pages repository, published on commit.
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'build/web/.'
          destination_folder: 'themedemo'
          destination_repo: 'rydmike/rydmike.github.io'
          user_email: 'm.rydstrom@gmail.com'
          user_name: 'rydmike'
